function setupTabs(){document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab').forEach(t=>t.classList.add('hidden'));$(b.dataset.tab).classList.remove('hidden');renderAll();});}
function renderDayBuilder(){const count=Number($('setDayCount')?.value||settings.days.length||1);const holder=$('dayBuilder');if(!holder)return;const days=[...settings.days];while(days.length<count)days.push({date:'',label:`Day ${days.length+1}`,sessions:['Morning Session','Afternoon Session']});holder.innerHTML=days.slice(0,count).map((d,i)=>`<div class="dayCard"><h3>Day ${i+1}</h3><div class="two"><div class="field"><label>Date</label><input type="date" id="dayDate${i}" value="${d.date||''}"></div><div class="field"><label>Day Label</label><input id="dayLabel${i}" value="${d.label||`Day ${i+1}`}"></div></div><div class="two"><div class="field"><label>Session 1</label><input id="daySession1_${i}" value="${d.sessions?.[0]||''}" placeholder="Morning Camp 9:00-12:00"></div><div class="field"><label>Session 2 (optional)</label><input id="daySession2_${i}" value="${d.sessions?.[1]||''}" placeholder="Afternoon Camp 1:00-4:00"></div></div></div>`).join('');}
function applySettingsToUI(){$('activityTitle').textContent=settings.activityName;$('activitySub').textContent=`${settings.activityType} • up to 5 days and 2 sessions per day`;$('setActivityName').value=settings.activityName;$('setActivityType').value=settings.activityType;$('setDayCount').value=String(settings.days.length);if($('secondarySourceName'))$('secondarySourceName').value=settings.secondarySourceName||'Other Source';updateSecondarySourceLabels();['srcPublic','srcSwarm','methodQR','methodMembership','methodManual','ruleWaiver','ruleWaiverPublic','ruleWaiverSwarm','ruleHomework','ruleArrival','ruleSwarmEligible'].forEach(id=>{if($(id))$(id).checked=!!settings[id];});$('scanPanel').classList.toggle('hidden',!(settings.methodQR||settings.methodMembership));renderDayBuilder();const df=$('dayFilter'),oldDay=df.value;df.innerHTML=settings.days.map(d=>`<option value="${d.date}">${formatDayLabel(d)}</option>`).join('');df.value=settings.days.some(d=>d.date===oldDay)?oldDay:(settings.days[0]?.date||today());onDayChange(false);}
function onDayChange(doRender=true){const day=settings.days.find(d=>d.date===selectedDay())||settings.days[0];const sf=$('sessionFilter'),old=sf.value;sf.innerHTML=(day?.sessions||[]).filter(Boolean).map(s=>`<option value="${s}">${s}</option>`).join('');if([...sf.options].some(o=>o.value===old))sf.value=old;$('datePill').textContent=formatDayLabel(day||{date:today(),label:'Today'});if(doRender)renderAll();}
function updateSecondarySourceLabels(){
  const name=clean($('secondarySourceName')?.value)||settings.secondarySourceName||'Other Source';
  if($('secondarySourceLabel'))$('secondarySourceLabel').textContent=`${name} Roster / Registration CSV`;
  if($('secondaryUploadBtn'))$('secondaryUploadBtn').textContent=`Upload ${name} CSV`;
  if($('secondarySourceHelp'))$('secondarySourceHelp').textContent=`Select the CSV exported from ${name}.`;
  if($('srcSwarmLabel'))$('srcSwarmLabel').textContent=`${name} registrations / roster`;
}
function saveSettings(){settings.activityName=clean($('setActivityName').value)||'MSS Attendance';settings.activityType=$('setActivityType').value;settings.secondarySourceName=clean($('secondarySourceName')?.value)||'Other Source';const count=Number($('setDayCount').value);settings.days=[];for(let i=0;i<count;i++){const date=$(`dayDate${i}`).value||today();const label=clean($(`dayLabel${i}`).value)||`Day ${i+1}`;const sessions=[clean($(`daySession1_${i}`).value),clean($(`daySession2_${i}`).value)].filter(Boolean);settings.days.push({date,label,sessions:sessions.length?sessions:['Session 1']});}['srcPublic','srcSwarm','methodQR','methodMembership','methodManual','ruleWaiver','ruleWaiverPublic','ruleWaiverSwarm','ruleHomework','ruleArrival','ruleSwarmEligible'].forEach(id=>settings[id]=!!$(id).checked);save();applySettingsToUI();renderAll();alert('Multi-day setup saved.');}
function resetSettings(){localStorage.removeItem(LS+'settings');location.reload();}
function renderSourceFilter(){const el=$('typeFilter');if(!el)return;const old=el.value;const sources=[...new Set(people.map(p=>clean(p.source)).filter(Boolean))].sort();el.innerHTML='<option value="all">All Sources</option>'+sources.map(src=>`<option value="${src.replace(/"/g,'&quot;')}">${src}</option>`).join('');if([...el.options].some(o=>o.value===old))el.value=old;}
function personCard(p){const needs=needsWaiver(p),checked=isChecked(p),arrival=arrivalFor(p);return `<div class="person ${checked?'checked':''} ${needs?'blocked':''}"><div class="name">${p.name||'(No name)'}</div><div class="meta">${p.source||p.type}${p.team?' • '+p.team:''} • ${selectedSession()}</div><div class="badges"><span class="badge ${p.source==='MSS'?'public':'swarm'}">${p.source||p.type}</span>${checked?`<span class="badge good">Checked ${arrival}</span>`:'<span class="badge neutral">Not checked</span>'}${!requiresWaiver(p)?'<span class="badge neutral">Waiver Not Required</span>':(p.waiver?'<span class="badge good">Waiver</span>':'<span class="badge warn">Needs Waiver</span>')}${p.homework?'<span class="badge good">Homework</span>':''}</div><div class="small">Parent: ${p.parent||'—'}<br>Email: ${p.email||'—'}<br>Phone: ${p.phone||'—'}</div><div class="row" style="margin-top:10px"><button class="btn ${checked?'secondary':'green'}" onclick="toggleCheck('${p.id}')">${checked?'Undo':'Check In'}</button><button class="btn secondary" onclick="toggleHomework('${p.id}')">Homework</button><button class="btn secondary" onclick="startWaiver('${p.id}')">Waiver</button></div></div>`;}
function renderPeople(){const v=visiblePeople();$('peopleList').innerHTML=v.map(personCard).join('')||'';$('filterMsg').classList.toggle('hidden',!!v.length||!people.length);$('filterMsg').textContent=people.length?'No participants match this day/session/source/search. Try Clear Filters.':'No participants loaded yet.';}
function renderKpis(){const checked=people.filter(p=>isChecked(p)).length;$('kRegistered').textContent=people.length;$('kChecked').textContent=checked;$('kWaiver').textContent=people.filter(p=>needsWaiver(p)).length;$('kHomework').textContent=people.filter(p=>p.homework).length;}
function renderTables(){const rows=people.slice(0,300).map(p=>`<tr><td>${p.name}</td><td>${p.type}</td><td>${p.team||''}</td><td>${p.session||''}</td><td>${p.email||''}</td><td>${p.phone||''}</td><td>${p.source||''}</td></tr>`).join('');$('importTable').innerHTML=`<table><tr><th>Name</th><th>Type</th><th>Team</th><th>Registered Session</th><th>Email</th><th>Phone</th><th>Source</th></tr>${rows}</table>`;$('waiverTable').innerHTML=`<table><tr><th>Name</th><th>Type</th><th>Status</th><th>Action</th></tr>${people.map(p=>`<tr><td>${p.name}</td><td>${p.type}</td><td>${!requiresWaiver(p)?'Not Required':(p.waiver?'Complete':'Missing')}</td><td><button class="btn secondary" onclick="startWaiver('${p.id}')">Open</button></td></tr>`).join('')}</table>`;$('homeworkTable').innerHTML=`<table><tr><th>Name</th><th>Type</th><th>Team</th><th>Homework</th><th>Action</th></tr>${people.map(p=>`<tr><td>${p.name}</td><td>${p.type}</td><td>${p.team}</td><td>${p.homework?'Complete':'Pending'}</td><td><button class="btn secondary" onclick="toggleHomework('${p.id}')">Toggle</button></td></tr>`).join('')}</table>`;}
function clearFilters(){$('typeFilter').value='all';$('statusFilter').value='all';$('search').value='';renderAll();}
function renderAll(){renderSourceFilter();renderKpis();renderPeople();renderTables();renderComm();renderTracker();renderReports();}
